### PR TITLE
234-fix: Missing favicon display

### LINKED ISSUE #234: Fix missing icon display
The site icon is not displayed

Image

### PR DESCRIPTION
**Pull request by ya6**
## What type of PR is this? (select all that apply)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 🚧 Breaking Change
- [ ] 🧑‍💻 Code Refactor
- [ ] 📝 Documentation Update

## Description

- add a set of icons
- server responds with the wrong type and as a result the icon is not displayed

## Related Tickets & Documents

- Related Issue #234
- Closes #234

## Screenshots, Recordings
icon-server-issue

_Please replace this line with any relevant images for UI changes._

## Added/updated tests?

- [ ] 👌 Yes
- [x] 🙅‍♂️ No, because they aren't needed
- [ ] 🙋‍♂️ No, because I need help

### CODE REVIEW

**Review by natanchik — APPROVED** [review]
It looks like this problem is gone 👍:
image

**Comment by ya6** [comment]
icon-server-issue

- the server receives a response of the wrong type and as a result the icon is not displayed

**Comment by apalchys** [comment]
@ya6 keep it as is. I will make change on infra side to support icons in the root.

**Comment by apalchys** [comment]
Fixed. https://pr249.rs.school/favicon.ico

**Comment by ya6** [comment]
> @ya6 keep it as is. I think you did it right in the latest version. I will make change on infra side to support icons in the root.

Ok, this was to find a solution from the client side

**Review by dzmitry-varabei — APPROVED** [review]

**Pull request merged**
